version: "3.8"

services:
  postgresql:
    image: postgres:16
    env_file: ./.env
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  app:
    depends_on:
      - postgresql
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://postgresql:${POSTGRES_DOCKER_PORT}/${POSTGRES_DATABASE}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}"
        }'
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  pgadmin: { }
  postgresql: { }

networks:
  backend: { }